let Leonardo = sprites.create(img`
    ................
    ................
    ................
    ......ffff......
    .....f7777f.88..
    .....8f88f88....
    .....f7777f.88..
    .....f7227f.....
    ......ffff......
    ...ffffeeffff...
    ..f77efeefe77f..
    .f7ffffffffff7f.
    f7f.fefeefef.f7f
    ff..ffffffff..ff
    ....fefeefef....
    ....ffffffff....
    ....f7f..f7f....
    ...ff7f..f7ff...
    ...f77f..f77f...
    ...ffff..ffff...
    `, SpriteKind.Player)
scene.setBackgroundColor(9)
